//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MedHelp.Infrastructure.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class MRIImage
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MRIImage()
        {
            this.MRIImage1 = new HashSet<MRIImage>();
        }
    
        public decimal Id { get; set; }
        public string Name { get; set; }
        [Display(Name = "Uploaded Date")]
        public System.DateTime UploadedDate { get; set; }
        public Nullable<decimal> FullScanId { get; set; }
        public string Image { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MRIImage> MRIImage1 { get; set; }
        public virtual MRIImage MRIImage2 { get; set; }
    }
}
